### ISSUE TITLE
Test files not migrated

### ISSUE THREAD

**Issue by bufdev** [golang/open2opaque#3]
`open2opaque rewrite -levels=red ./...` does not rewrite `_test.go` files, although the help documentation from `open2opaque rewrite -h` hints that it should. The usefulness of the tool is significantly less without test rewrites.

**Comment by stapelberg** [comment]
Thanks for your report! This is fixed in open2opaque v0.1.1 (use `go install google.golang.org/open2opaque@v0.1.1` to install).
